#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 1.9.{build}.0
install:
    - git clone https://github.com/PowerShell/DscResource.Tests

    - ps: |
        $moduleName = 'LifecycleDsc'
        $mainModuleFolder = "Modules\$moduleName"
        Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorInstallTask -PesterMaximumVersion 4.0.8

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: off

test_script:
# Invoke DSC configuration!
  - ps: . .\Tests\appveyor.dsc.ps1
# Test with native PS version, finalize
  - ps: . .\Tests\appveyor.pester.ps1 -Test -Finalize

deploy_script:
  - ps: Get-Content .\Artifacts.txt | Foreach-Object { Push-AppveyorArtifact $_ }